language: ruby
script: bin/rspec
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
env:
  - FARADAY_ADAPTER=net_http
  - FARADAY_ADAPTER=em_http
notifications:
  email: false
gemfile:
  - gemfiles/Gemfile.faraday-0.8
  - Gemfile
